-- ============================================================================
-- 0019_reply_state.sql — remember that someone is waiting, after the cache goes
-- ============================================================================
-- A conflict between two rules the portal has to honour at once:
--
--   Upwork's terms: "Caching API responses for more than 24 hours is not
--   allowed." expire_upwork_mirror() therefore hard-deletes up_messages past the
--   self-imposed 12h, and sync only re-fetches rooms whose latest_story_id
--   changed — a quiet room's messages go and never come back.
--
--   The wait meter: needs to know a client has been waiting 26 hours.
--
-- Built on the mirror, the meter could not work. Once the unanswered message was
-- expired the room read as answered, so the row dropped off "Needs reply" at
-- exactly the moment it mattered, and the Breached-24h level was unreachable.
-- Measured on live data it was firing on 4 of 423 conversations.
--
-- The resolution is the Zone 1 / Zone 2 split this schema already runs on. We do
-- not need to keep Upwork's message content past 24 hours; we need to keep a
-- fact we derived from it — "at 11:02 IST the newest message in this room was
-- inbound". That is a timestamp and a label, generated by the portal, holding no
-- Upwork copy: portal-owned data, not a cached response. The bodies still expire
-- on schedule.
--
-- So sync writes this table every time it sees a room's messages, and the meter
-- reads only this table. One source, and it survives the cache.
-- ============================================================================

create table if not exists public.room_reply_state (
  room_id          text        primary key,
  -- When the unanswered inbound message was sent. Null means answered.
  awaiting_since   timestamptz,
  -- Which signal in src/lib/upwork/direction.ts attributed that message.
  -- 'alternation' means the wait is a guess and the UI must show it as one.
  attribution      text,
  last_outbound_at timestamptz,
  message_count    integer     not null default 0,
  -- We held messages but could not attribute a single one.
  all_unknown      boolean     not null default false,
  -- When the portal last confirmed this against live data.
  observed_at      timestamptz not null default now()
);

-- Deliberately NO foreign key to up_rooms. That table is Zone 1 and gets
-- deleted on expiry; a cascade would take this derived state with it, which is
-- the whole thing this table exists to prevent.
comment on table public.room_reply_state is
  'Portal-derived reply state per conversation: is the client waiting, since when, how confidently. Survives up_messages expiry because it holds no Upwork content — only a timestamp and an attribution label the portal worked out itself.';

create index if not exists room_reply_state_awaiting_idx
  on public.room_reply_state (awaiting_since)
  where awaiting_since is not null;

alter table public.room_reply_state enable row level security;

-- Same rule as everywhere else: you see a room's state if you can see the room.
drop policy if exists room_reply_state_read on public.room_reply_state;
create policy room_reply_state_read on public.room_reply_state
  for select using (public.can_see_target('room', room_id));

grant select on public.room_reply_state to authenticated, anon;
grant all on public.room_reply_state to service_role;

-- ---------------------------------------------------------------------------
-- The meter now reads the derived state, not the expiring mirror
-- ---------------------------------------------------------------------------
-- Column names are unchanged on purpose so src/lib/wait.ts and the UI do not
-- have to care where the facts came from.
--
-- Scoping note, from 0016: a view reads its base tables with the OWNER's
-- privileges, so the RLS policy above does NOT apply here. Filter explicitly.
drop view if exists public.v_room_wait;

create view public.v_room_wait as
  select
    s.room_id,
    s.awaiting_since                          as last_inbound_at,
    s.last_outbound_at,
    s.message_count,
    (s.awaiting_since is not null)             as awaiting_reply,
    s.awaiting_since                           as waiting_since,
    s.attribution                              as waiting_source,
    s.all_unknown                              as direction_unknown,
    s.observed_at
  from public.room_reply_state s
  where public.can_see_target('room', s.room_id);

comment on view public.v_room_wait is
  'Per-room reply state for the wait meter, scoped to rooms the caller can see. Severity is computed in src/lib/wait.ts because the ramp discounts overnight IST hours.';

grant select on public.v_room_wait to authenticated, anon;

-- ---------------------------------------------------------------------------
-- Seed from whatever the mirror currently holds
-- ---------------------------------------------------------------------------
-- One-off so the meter is not blank until every room has been re-synced. Rooms
-- whose messages already expired are simply absent, and sync fills them in.
insert into public.room_reply_state
  (room_id, awaiting_since, attribution, last_outbound_at, message_count, all_unknown, observed_at)
select
  t.room_id,
  case when t.li_at is not null and (t.lo_at is null or t.lo_at < t.li_at) then t.li_at end,
  case when t.li_at is not null and (t.lo_at is null or t.lo_at < t.li_at) then t.li_src end,
  t.lo_at,
  t.total,
  (t.total > 0 and t.decided = 0),
  now()
from (
  select
    r.room_id,
    (select m.sent_at from public.up_messages m
      where m.room_id = r.room_id and m.direction = 'inbound' and not m.is_system
      order by m.sent_at desc nulls last limit 1) as li_at,
    (select m.direction_source from public.up_messages m
      where m.room_id = r.room_id and m.direction = 'inbound' and not m.is_system
      order by m.sent_at desc nulls last limit 1) as li_src,
    (select max(m.sent_at) from public.up_messages m
      where m.room_id = r.room_id and m.direction = 'outbound' and not m.is_system) as lo_at,
    (select count(*) from public.up_messages m
      where m.room_id = r.room_id and not m.is_system) as total,
    (select count(*) from public.up_messages m
      where m.room_id = r.room_id and not m.is_system and m.direction <> 'unknown') as decided
  from public.up_rooms r
) t
where t.total > 0
on conflict (room_id) do nothing;
